import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from "../components/Footer"
import Nav from "../components/Nav"
import dynamic from 'next/dynamic'
import Link from 'next/link'

const CatalogComponent = dynamic(()=> import("shop/Catalog"), {
  ssr: false,
})
// const ClientFrontApp = dynamic(()=> import("frontend/ClientFrontApp"), {
//   ssr: false,
// });


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
           href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
           rel="stylesheet"
         />
         <link
           href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
           rel="stylesheet"
         />
        <link rel="icon" href="https://www.fravega.com/static/iso_fvg@2x.png" />
      </Head>
      <Nav />
      
      <main className={styles.main}>
        {/* <ClientFrontApp /> */}
        <h1 className={styles.title}>
          Welcome to the main app port: 3000
        </h1> 
        <Link href="/catalogOnMain">Go to catalog</Link>

    Component from shop
    <CatalogComponent/>

      </main>

      <Footer/>
    </div>
  )
}
